// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScanWorker.Data;

#nullable disable

namespace ScanWorker.Migrations
{
    [DbContext(typeof(ScanWorkerContext))]
    [Migration("20260221025056_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScanWorker.Data.Models.EventProcessingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("LastProcessedEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("EventProcessingState", (string)null);
                });

            modelBuilder.Entity("ScanWorker.Data.Models.Parcel", b =>
                {
                    b.Property<int>("ParcelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ParcelId");

                    b.ToTable("Parcels", (string)null);
                });

            modelBuilder.Entity("ScanWorker.Data.Models.ScanEvent", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("ParcelId")
                        .HasColumnType("int");

                    b.Property<string>("RunId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedDateTimeUtc")
                        .HasDatabaseName("IX_ScanEvents_CreatedDateTimeUtc");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_ScanEvents_ParcelId");

                    b.HasIndex("ParcelId", "Type")
                        .HasDatabaseName("IX_ScanEvents_ParcelId_Type");

                    b.ToTable("ScanEvents", (string)null);
                });

            modelBuilder.Entity("ScanWorker.Data.Models.ScanEvent", b =>
                {
                    b.HasOne("ScanWorker.Data.Models.Parcel", "Parcel")
                        .WithMany("ScanEvents")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("ScanWorker.Data.Models.Parcel", b =>
                {
                    b.Navigation("ScanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
