// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ScanWorker.Migrations
{
    [DbContext(typeof(ScanWorkerContext))]
    [Migration("20260220111053_deviceIDchangeToString")]
    partial class deviceIDchangeToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScanWorker.Data.Models.EventProcessingState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("LastProcessedEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("EventProcessingState", (string)null);
                });

            modelBuilder.Entity("ScanWorker.Data.Models.Parcels", b =>
                {
                    b.Property<int>("ParcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParcelId"));

                    b.Property<DateTime?>("DeliveryDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEventCreatedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastEventId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LastEventStatusCode")
                        .HasColumnType("int");

                    b.Property<int>("LastEventType")
                        .HasColumnType("int");

                    b.Property<string>("LastRunId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PickupDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ParcelId");

                    b.HasIndex("UserId");

                    b.ToTable("Parcels", (string)null);
                });

            modelBuilder.Entity("ScanWorker.Data.Models.ScanEvents", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParcelId")
                        .HasColumnType("int");

                    b.Property<string>("RunId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedDateTimeUtc")
                        .HasDatabaseName("IX_ScanEvents_CreatedDateTimeUtc");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_ScanEvents_ParcelId");

                    b.HasIndex("UserId");

                    b.ToTable("ScanEvents", (string)null);
                });

            modelBuilder.Entity("ScanWorker.Data.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CarrierId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ScanWorker.Data.Models.Parcels", b =>
                {
                    b.HasOne("ScanWorker.Data.Models.User", "User")
                        .WithMany("Parcels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScanWorker.Data.Models.ScanEvents", b =>
                {
                    b.HasOne("ScanWorker.Data.Models.Parcels", "Parcel")
                        .WithMany("ScanEvents")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScanWorker.Data.Models.User", "User")
                        .WithMany("ScanEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parcel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScanWorker.Data.Models.Parcels", b =>
                {
                    b.Navigation("ScanEvents");
                });

            modelBuilder.Entity("ScanWorker.Data.Models.User", b =>
                {
                    b.Navigation("Parcels");

                    b.Navigation("ScanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
